routes:
    home:
        method: 'get'
        path: '/'
        action: 'Gallery\Controller\BasicPageController::homeAction'
    images:
        method: 'get'
        path: '/image/'
        action: 'Gallery\Controller\ImageController::indexAction'
    add_image:
        method: 'match'
        path: '/image/add'
        action: 'Gallery\Controller\ImageController::addAction'
    edit_image:
        method: 'match'
        path: '/image/{id}/edit'
        action: 'Gallery\Controller\ImageController::editAction'
        required:
            id: '\d+'
    delete_image:
        method: 'match'
        path: '/image/{id}/delete'
        action: 'Gallery\Controller\ImageController::deleteAction'
        required:
            id: '\d+'
