routes:
    home:
        method: 'get'
        path: '/'
        action: 'Gallery\Controller\BasicPageController::homeAction'
    images:
        method: 'get'
        path: '/image'
        action: 'Gallery\Controller\ImageController::indexAction'
    add_image:
        method: 'match'
        path: '/image/add'
        action: 'Gallery\Controller\ImageController::addAction'
